# Generated by Django 3.2.9 on 2022-09-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_rename_name_company_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(blank=True, choices=[('RELIANCE', 'RELIANCE'), ('SBIN', 'SBIN'), ('INFY', 'INFY')], max_length=30),
        ),
    ]
